BEGIN;

--
--  Add delegator info
--

CREATE TABLE IF NOT EXISTS aleo_rewards.delegator_info (
  id                          bigint                  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  address                     text                    NOT NULL,
  created_at                  timestamptz             NOT NULL DEFAULT now(),
  updated_at                  timestamptz             NOT NULL DEFAULT now(),

  UNIQUE(address)
);

ALTER TABLE aleo_rewards.delegator_info OWNER TO ${aleo_rewards_owner_role};
GRANT ALL PRIVILEGES ON TABLE aleo_rewards.delegator_info TO ${aleo_rewards_app_role};

--
--  Add validator info
--

CREATE TABLE IF NOT EXISTS aleo_rewards.validator_info (
  id                          bigint                  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  address                     text                    NOT NULL,
  created_at                  timestamptz             NOT NULL DEFAULT now(),
  updated_at                  timestamptz             NOT NULL DEFAULT now(),

  UNIQUE(address)
);

ALTER TABLE aleo_rewards.validator_info OWNER TO ${aleo_rewards_owner_role};
GRANT ALL PRIVILEGES ON TABLE aleo_rewards.validator_info TO ${aleo_rewards_app_role};

--
--  Add block info
--

CREATE TABLE IF NOT EXISTS aleo_rewards.block_info (
  id                          bigint                  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at                  timestamptz             NOT NULL DEFAULT now(),
  updated_at                  timestamptz             NOT NULL DEFAULT now()
);

ALTER TABLE aleo_rewards.block_info OWNER TO ${aleo_rewards_owner_role};
GRANT ALL PRIVILEGES ON TABLE aleo_rewards.block_info TO ${aleo_rewards_app_role};

--
--  Add transaction info
--

CREATE TABLE IF NOT EXISTS aleo_rewards.transaction_info (
  id                          bigint                  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at                  timestamptz             NOT NULL DEFAULT now(),
  updated_at                  timestamptz             NOT NULL DEFAULT now()
);

ALTER TABLE aleo_rewards.transaction_info OWNER TO ${aleo_rewards_owner_role};
GRANT ALL PRIVILEGES ON TABLE aleo_rewards.transaction_info TO ${aleo_rewards_app_role};